# Custom Language File for Launcher Customizer

[ejs.app]
title = "NexuxNova Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU NEXUXNOVA"
welcomeDescription = "Sei a pochi passi da NexuxNova Launcher"
welcomeDescCTA = "Copyright © 2025 NexuxNova"
